---
# Main installation File
#
- import_tasks: docker_centos.yml
  when: ansible_os_family == "RedHat"

- import_tasks: docker_ubuntu.yml
  when: ansible_os_family == "Ubuntu" or ansible_os_family == "Debian"

- name: install docker
  package:
    name: docker-ce
    state: "{{ docker_state }}"
    update_cache:  yes
#  notify:
#    - start docker

# start docker
- name: start docker
  service:
    name: docker
    state: started
    enabled: yes
