---
# Main installation File
#
- import_tasks: docker_cenos.yml
  when: ansible_os_family == "RedHat"

- import_tasks: docker_ubuntu.yml
  when: ansible_os_family == "Ubuntu" or ansible_os_family == "Debian"

- name: install docker
  yum:
    name: docker-ce
    state: "{{ docker_state }}"
    update_cache:  yes
